esphome:
  name: toshiba
  friendly_name: tu2c-link
  platformio_options:
    board_build.flash_mode: dio

# external_components:
#   - source:
      # type: git
      # url: https://github.com/theeuwke/esphome-tu2c-link.git
      # ref: main
    # refresh: 1s

external_components:
  - source:
      type: local
      path: ./components

uart:
  id: uart_bus
  baud_rate: 2400
  rx_pin: GPIO4
  tx_pin: GPIO5         # optional if you only receive
  rx_buffer_size: 512
  parity: EVEN
  debug:
    direction: RX
    dummy_receiver: true
    after:
      timeout: 50ms     # publish accumulated bytes after 100 ms of silence
    sequence:
      # default action logs hex, but here we explicitly call the helper:
      - lambda: |-
          UARTDebug::log_hex(direction, bytes, ' ');
esp32:
  variant: esp32c3
  board: lolin_c3_mini
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "mwAk5tRXIrhkzqDzJA2hVWYR1sxt/bzVOs1VA2z7hu8="

ota:
  - platform: esphome
    password: "5fb1205e70155d9d2920b75e9fc95cff"

wifi:
  ssid: "B&A.TB"
  password: "bartjeenliesje"
  ap: {}

  manual_ip:
  # Set this to the IP of the ESP
    static_ip: 192.168.178.110
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.178.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

captive_portal:
    
#climate:
#  - platform: tu2c_link
#    name: "Toshiba AC"
#    id: toshiba_ac
#    connected:
#      name: "Toshiba Estia R32 Connected"
#    failed_crcs:
#      name: "Toshiba Estia R32 Failed CRCs"
#    vent:
#      name: "Toshiba Estia R32 Vent Switch"

# light:
#  - platform: esp32_rmt_led_strip
#    id: c3_mini_wled
#    chipset: ws2812
#    num_leds: 1
#    pin: GPIO7
#    name: "${friendly_name} led"
#    rmt_channel: 0
#    rgb_order: GRB

logger:
  level: DEBUG
  hardware_uart: USB_SERIAL_JTAG
  baud_rate: 0



web_server:
  port: 80
  include_internal: true

# Text sensor shown on the web UI
text_sensor:
  - platform: template
    id: uart_hex
    name: "UART RX (HEX)"
    update_interval: never  

toshiba_log:
